easy_admin:
   entities:
      Product:
          class: App\Entity\Product
          list:
              fields:
                  - { property: 'id', type: 'integer' }
                  - { property: 'name', type: 'text' }
                  - { property: 'description', type: 'text' }
                  - { property: 'type' }
                  - { property: 'details' }
                  - { property: 'image', type: 'text' }
                  - { property: 'updatedAt' }
          form:
              fields:
                  - { property: 'name', type: 'text' }
                  - { property: 'description', type: 'text' }
                  - { property: 'technical_data' }
                  - { property: 'type' }
                  - { property: 'details' }
                  - { property: 'imageFile', type: 'vich_image' }
          
      ProductType:
          class: App\Entity\ProductType
          list:
              fields:
                  - { property: 'id', type: 'integer' }
                  - { property: 'title', type: 'text' }
                  - { property: 'image', type: 'text' }
                  - { property: 'description' }
                  - { property: 'details' }
                  - { property: 'created_at' }
                  - { property: 'products' }
          form:
              fields:
                  - { property: 'title', type: 'text' }
                  - { property: 'description' }
                  - { property: 'details' }
                  - { property: 'imageFile', type: 'vich_image' }
                  - { property: 'folderFile', type: 'vich_file' }

      User:
          class: App\Entity\User
          controller: App\Controller\UserAdminController

      Contact:
          class: App\Entity\Contact
          disabled_actions: ['new', 'edit']
          list:
              fields:
                  - { property: 'id', type: 'integer' }
                  - { property: 'name' }
                  - { property: 'email' }
                  - { property: 'subject' }
                  - { property: 'message' }
