vich_uploader:
    db_driver: orm

    mappings:
        product:
            uri_prefix: '%app.path.product%'
            upload_destination: '%kernel.project_dir%/public%app.path.product%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer