resources:
    App\Entity\ProductType:
        collectionOperations:
          get: ~
        itemOperations:
            get: ~
    App\Entity\Product:
        collectionOperations:
          get: ~
        itemOperations:
            get: ~